//! Responses the HTTP listener produces itself (M3 design §8): error pages,
//! the 1×1 GIF, 407 / 400 and the CONNECT success line.

use bytes::Bytes;
use http::{Response, StatusCode, header};
use http_body_util::combinators::BoxBody;
use http_body_util::{BodyExt, Empty, Full};

pub type ResponseBody = BoxBody<Bytes, hyper::Error>;

/// A 1×1 transparent GIF (43 bytes).
pub const TINY_GIF: [u8; 43] = [
    0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xff, 0xff, 0xff, 0x21, 0xf9, 0x04, 0x01, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x00, 0x01, 0x00, 0x00, 0x02, 0x02, 0x44, 0x01, 0x00, 0x3b,
];

pub fn full(bytes: Bytes) -> ResponseBody {
    Full::new(bytes).map_err(|never| match never {}).boxed()
}

pub fn empty() -> ResponseBody {
    Empty::<Bytes>::new()
        .map_err(|never| match never {})
        .boxed()
}

pub fn connect_established() -> Response<ResponseBody> {
    Response::builder()
        .status(StatusCode::OK)
        .body(empty())
        .expect("static response")
}

pub fn tiny_gif() -> Response<ResponseBody> {
    Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "image/gif")
        .header(header::CACHE_CONTROL, "no-store")
        .body(full(Bytes::from_static(&TINY_GIF)))
        .expect("static response")
}

pub fn proxy_auth_required() -> Response<ResponseBody> {
    Response::builder()
        .status(StatusCode::PROXY_AUTHENTICATION_REQUIRED)
        .header(header::PROXY_AUTHENTICATE, "Basic realm=\"rurge\"")
        .header(header::CONTENT_TYPE, "text/plain; charset=utf-8")
        .body(full(Bytes::from_static(b"proxy authentication required")))
        .expect("static response")
}

pub fn bad_request(msg: &str) -> Response<ResponseBody> {
    Response::builder()
        .status(StatusCode::BAD_REQUEST)
        .header(header::CONTENT_TYPE, "text/plain; charset=utf-8")
        .body(full(Bytes::from(msg.to_string())))
        .expect("static response")
}

pub struct ErrorPage<'a> {
    pub title: &'a str,
    pub session_id: u64,
    pub dst: String,
    pub rule: Option<String>,
    pub chain: Vec<String>,
    pub message: String,
}

fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '&' => out.push_str("&amp;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

/// The rurge error page: self-contained HTML, no external resources.
pub fn error_page(status: StatusCode, page: &ErrorPage<'_>) -> Response<ResponseBody> {
    let rule = page.rule.as_deref().unwrap_or("(none)");
    let chain = if page.chain.is_empty() {
        "(none)".to_string()
    } else {
        page.chain.join(" > ")
    };
    let html = format!(
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>rurge: {title}</title>\
<style>body{{font-family:system-ui,sans-serif;margin:3em auto;max-width:40em;color:#222}}code{{background:#f3f3f3;padding:.1em .3em}}</style></head>\
<body><h1>{title}</h1><p>{message}</p><table>\
<tr><td>Destination</td><td><code>{dst}</code></td></tr>\
<tr><td>Rule</td><td><code>{rule}</code></td></tr>\
<tr><td>Policy</td><td><code>{chain}</code></td></tr>\
<tr><td>Session</td><td><code>{id}</code></td></tr></table>\
<p style=\"color:#888\">Generated by rurge</p></body></html>",
        title = escape(page.title),
        message = escape(&page.message),
        dst = escape(&page.dst),
        rule = escape(rule),
        chain = escape(&chain),
        id = page.session_id,
    );
    Response::builder()
        .status(status)
        .header(header::CONTENT_TYPE, "text/html; charset=utf-8")
        .header(header::CACHE_CONTROL, "no-store")
        .body(full(Bytes::from(html)))
        .expect("static response")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn responses_have_the_expected_shape() {
        let gif = tiny_gif();
        assert_eq!(gif.status(), 200);
        assert_eq!(gif.headers()[header::CONTENT_TYPE], "image/gif");
        let body = gif.into_body().collect().await.unwrap().to_bytes();
        assert_eq!(body.len(), 43);
        assert_eq!(&body[..6], b"GIF89a");
        let auth = proxy_auth_required();
        assert_eq!(auth.status(), 407);
        assert_eq!(
            auth.headers()[header::PROXY_AUTHENTICATE],
            "Basic realm=\"rurge\""
        );
        let page = error_page(
            StatusCode::FORBIDDEN,
            &ErrorPage {
                title: "Rejected",
                session_id: 7,
                dst: "ads.example:443".to_string(),
                rule: Some("DOMAIN-SUFFIX,<ads>.example,REJECT".to_string()),
                chain: vec!["Block".to_string(), "REJECT".to_string()],
                message: "rejected by policy".to_string(),
            },
        );
        assert_eq!(page.status(), 403);
        let html = String::from_utf8(
            page.into_body()
                .collect()
                .await
                .unwrap()
                .to_bytes()
                .to_vec(),
        )
        .unwrap();
        assert!(
            html.contains("&lt;ads&gt;.example")
                && html.contains("Block &gt; REJECT")
                && html.contains("<code>7</code>"),
            "{html}"
        );
        assert_eq!(connect_established().status(), 200);
        assert_eq!(bad_request("nope").status(), 400);
    }
}
